@startuml
!pragma layout smetana
skinparam dpi 150
skinparam defaultFontName Arial
skinparam shadowing false
skinparam monochrome true
skinparam linetype ortho
package "Интерфейс" {
 class ЭкранПриёмкиТСД <<boundary>>
 class ЭкранПланаЗакупок <<boundary>>
 class ЭкранСроков <<boundary>>
 class ЭкранОтчётов <<boundary>>
}
package "Управление" {
 class КонтроллерПриёмки <<control>>
 class СервисПланированияЗакупок <<control>>
 class СервисПрогнозирования <<control>>
 class СервисСроковИУценки <<control>>
 class СервисАналитики <<control>>
 class АдаптерКасс <<control>>
 class АдаптерИнтернетМагазина <<control>>
}
package "Сущности" {
 class Товар <<entity>> {
  наименование
  срокРеализации
  кратность
 }
 class Поставщик <<entity>> {
  срокПоставки
  минСумма
 }
 class УсловиеПоставки <<entity>>
 class ЗаказПоставщику <<entity>> {
  дата
  статус
 }
 class Партия <<entity>> {
  годенДо
  остаток
 }
 class Продажа <<entity>>
 class Списание <<entity>>
 class Прогноз <<entity>> {
  P50
  P80
  P95
 }
 class МодельПрогноза <<entity>>
}
ЭкранПриёмкиТСД --> КонтроллерПриёмки
ЭкранПланаЗакупок --> СервисПланированияЗакупок
ЭкранСроков --> СервисСроковИУценки
ЭкранОтчётов --> СервисАналитики
СервисПланированияЗакупок --> Прогноз
СервисПланированияЗакупок --> ЗаказПоставщику
СервисПрогнозирования --> МодельПрогноза
КонтроллерПриёмки --> Партия
СервисСроковИУценки --> Списание
АдаптерКасс --> Продажа
Поставщик "1" -- "0..*" УсловиеПоставки
Товар "1" -- "0..*" УсловиеПоставки
Поставщик "1" -- "0..*" ЗаказПоставщику
Товар "1" -- "0..*" Партия
ЗаказПоставщику "1" -- "0..*" Партия
Партия "1" -- "0..*" Продажа
Партия "1" -- "0..*" Списание
Товар "1" -- "0..*" Прогноз
МодельПрогноза "1" -- "0..*" Прогноз
@enduml
